In [ ]:
text = 'As I was waiting, a man came out of a side room, and at a glance I was sure he must be Long John. \
His left leg was cut off close by the hip, and under the left shoulder he carried a crutch, which he managed \
with wonderful dexterity, hopping about upon it like a bird. He was very tall and strong, with a face as big \
as a ham—plain and pale, but intelligent and smiling. Indeed, he seemed in the most cheerful spirits, whistling \
as he moved about among the tables, with a merry word or a slap on the shoulder for the more favoured of his guests.'

In [ ]:
text_low = text.lower()

In [4]:
text_low

'as i was waiting, a man came out of a side room, and at a glance i was sure he must be long john. his left leg was cut off close by the hip, and under the left shoulder he carried a crutch, which he managed with wonderful dexterity, hopping about upon it like a bird. he was very tall and strong, with a face as big as a ham—plain and pale, but intelligent and smiling. indeed, he seemed in the most cheerful spirits, whistling as he moved about among the tables, with a merry word or a slap on the shoulder for the more favoured of his guests.'

In [ ]:
import re

s = re.compile('[a-zA-Z]*')
l = [i for i in s.findall(text_low) if len(i)]

In [26]:
l = [1,2,3,3,2,4]
d = dict()

In [27]:
help(d.get)

Help on built-in function get:

get(key, default=None, /) method of builtins.dict instance
    Return the value for key if key is in the dictionary, else default.



In [28]:
for n in l:
    d[n] = d.get(n, 0)+1

In [29]:
d

{1: 1, 2: 2, 3: 2, 4: 1}

In [4]:
import re

import requests
from bs4 import BeautifulSoup

def getUrlSpecifyText(url='https://cn.udacity.com/courses/all'):
    l = []
    
    req = requests.get(url)
    
    soup = BeautifulSoup(req.text, 'lxml')
    
    summaries = soup.find_all('div', class_='course-summary-card')
    for tag in summaries:
        l_sub = []
        
        l_sub.append(tag.select_one('h3 a').get_text().strip())          # 课程名称
        
        r = tag.find_all('span', 'ng-star-inserted')                     # 课程等级
        l_sub.append(r[0].get_text().strip())
        try:
            l_sub.append(r[1].get_text().strip())                        # 课程简介
        except IndexError as e:
            l_sub.append('None')                                         # 简介为空，则设为‘None’
            continue
             
        l.append(l_sub)
        
    return l

In [6]:
getUrlSpecifyText()[:10]

[['AI 产品经理 (英)', '初级', '驱动 AI 产品商业化落地，用 AI 为业务赋能，成为炙手可热稀缺人才。'],
 ['数据挖掘 求职直通班',
  '中级',
  '从数据分析、机器学习开始，掌握推荐系统和大数据计算框架 Spark 等核心技能，通过学习、项目、拓展、案例和求职辅导，系统完善对接职场需求，一站式直达职业目标'],
 ['市场营销分析 (英)',
  '初级',
  '掌握市场营销所需的基本数据技能，使用 Google Analytics 和 Data Studio 呈现你的结论'],
 ['传感器融合 (英)', '高级', '和梅赛德斯-奔驰学习，成为掌握无人驾驶、物联网、机器人开发核心技术的抢手工程师。'],
 ['数据洞察与说服技巧 (英)', '中级', '掌握数据可视化呈现商业洞察，练就用数据影响决策的说服技巧。'],
 ['云计算软件开发 (英)',
  '中级',
  '学习在 AWS 上构建全栈应用，并使用 Kubernetes 和 Serverless 框架分发采用微服务的应用，成为炙手可热的云计算软件开发工程师。'],
 ['云计算 DevOps (英)',
  '中级',
  '学习在 AWS 上通过代码部署基础设施和应用，构建 CI/CD 管道，以及使用 Kubernetes 和其他现代工具运维化微服务，成为一名抢手的云计算 DevOps 工程师。'],
 ['AI 求职直通班',
  '中级',
  '一站掌握机器学习、深度学习、CV、NLP 等 AI 核心技能，覆盖金融风控、计算机视觉、自然语言处理、数据挖掘、计算广告、语音识别六大热门领域，高性价比对接职场需求'],
 ['C++ 程序设计 (英)', '中级', '全面提升面向对象编程能力，成为 C++ 程序设计的专家。'],
 ['数据结构与算法 (英)', '中级', '精选 100+ 道面试真题，挑战数据结构与算法习题，获得详细项目审阅反馈，轻松应对求职面试和工作挑战。']]

In [7]:
s = """NLP is a way for computers to analyze, understand, and derive meaning from human language in a smart and useful way. 
By utilizing NLP, developers can organize and structure knowledge to perform tasks such as automatic summarization, translation, 
named entity recognition, relationship extraction, sentiment analysis, speech recognition, and topic segmentation.
“Apart from common word processor operations that treat text like a mere sequence of symbols, NLP considers the hierarchical 
structure of language: several words make a phrase, several phrases make a sentence and, ultimately, sentences convey ideas,” 
John Rehling, an NLP expert at Meltwater Group, said in How Natural Language Processing Helps Uncover Social Media Sentiment. 
“By analyzing language for its meaning, NLP systems have long filled useful roles, such as correcting grammar, converting speech 
to text and automatically translating between languages.”"""

In [9]:
import re 

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

def getNormalizedText(text=s):
    s_c = re.sub('[^a-zA-Z0-9]', ' ', text)
    
    # tokenize
    words = word_tokenize(s_c)
    
    # stopwords
    w_s = [w for w in words if w not in stopwords.words('english')]
    
    return w_s

In [10]:
getNormalizedText()[:10]

['NLP',
 'way',
 'computers',
 'analyze',
 'understand',
 'derive',
 'meaning',
 'human',
 'language',
 'smart']

### nn

In [62]:
import numpy
import scipy.special

In [104]:
class neuralNetwork:
    # 初始化神经网络（各层节点数、学习率） --各层节点数、学习率、2个权重矩阵、激活函数
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 输入层、隐藏层、输出层的节点数量
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # 学习率
        self.lr = learningrate
        
        ## 权重矩阵（一列）  --numpy.random.normal
        # 权重数组中的w_i_j，表示链接是从下一层的节点i到节点j --使用正态分布采样权重
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 设置激活函数S -scipy.special.expit(x)
        self.activation_function = lambda x: 1/(1+numpy.exp(-x))
        
        pass
    
    # 训练神经网络（训练数据集整理后的输入列表，目标数值列表） --train数据集输入，训练神经网络，调整权重
    def train(self, inputs_list, targets_list):
        # 将输入列表转换为二维数组并转置
        # 将目标列表转换为二维数组并转置
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        
        # 矩阵点乘法--计算进入隐藏层的信号
        # 激活函数--计算离开隐藏层的信号
        hidden_inputs = numpy.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # 矩阵点乘法--计算进入最终输出层的信号
        # 激活函数--计算离开最终输出层的信号（最终输出）
        final_inputs = numpy.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        print('final_outputs', final_outputs)
        
        # 隐蔽层和最终层的误差
        # 输入层和隐藏层的误差
        print('targets', targets)
        output_errors = targets - final_outputs
        print('output_errors', output_errors)
        hidden_errors = numpy.dot(self.who.T, output_errors) 
        print('hidden_errors', hidden_errors)
        
        # 为隐藏层和最终层间权重矩阵进行更新
        # 为输入层和隐藏层间权重矩阵进行更新
        print('who_term', (output_errors * final_outputs * (1.0 - final_outputs)))
        print('wih_term', (hidden_errors * hidden_outputs * (1.0 - hidden_outputs)))
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        
        
    # 查询神经网络（测试数据集整理后的输入列表） --训练后，test数据集输入，返回计算得出的检验样本集最终输出
    def query(self, inputs_list):
        # 将输入列表转换为二维数组并转置
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # 矩阵点乘法--计算进入隐藏层的信号
        # 激活函数--计算离开隐藏层的信号
        hidden_inputs = numpy.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # 矩阵点乘法--计算进入最终输出层的信号
        # 激活函数--计算离开最终输出层的信号（最终输出）
        final_inputs = numpy.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        # 返回最终输出列表
        return final_outputs
    
        pass

In [105]:
x = np.arange(4).reshape((2,2))

x

array([[0, 1],
       [2, 3]])

In [106]:
numpy.transpose(x)

array([[0, 2],
       [1, 3]])

In [107]:
x.T

array([[0, 2],
       [1, 3]])

#### nn-data

In [109]:
import numpy as np
x = np.array([[0.5, -0.2, 0.1]])
target = np.array([[0.4]])
learnrate = 0.5

# 3*2
weights_input_hidden = np.array([[0.1, -0.2],
                                 [0.4, 0.5],
                                 [-0.3, 0.2]]).T
# 2*1
weights_hidden_output = np.array([[0.3],
                                  [-0.1]]).T

delta_weights_i_h = np.zeros(weights_input_hidden.shape)
delta_weights_h_o = np.zeros(weights_hidden_output.shape)

In [110]:
weights_input_hidden, weights_hidden_output

(array([[ 0.1,  0.4, -0.3],
        [-0.2,  0.5,  0.2]]), array([[ 0.3, -0.1]]))

#### 实例化（测试train）

In [111]:
nn = neuralNetwork(3,2,1,0.1)

nn.wih = weights_input_hidden.copy()
nn.who = weights_hidden_output.copy()

In [112]:
# 转为list of list
X = list(x[0])
y = list(target[0])

X, y

([0.5, -0.2, 0.1], [0.4])

In [113]:
nn.train(x, target)

final_outputs [[0.5249765]]
targets [[0.4]]
output_errors [[-0.1249765]]
hidden_errors [[-0.03749295]
 [ 0.01249765]]
who_term [[-0.03116616]]
wih_term [[-0.00936481]
 [ 0.00309924]]


In [87]:
nn.who

array([[ 0.29848843, -0.10141844]])

In [88]:
nn.wih

array([[ 0.09953176,  0.4001873 , -0.30009365],
       [-0.19984504,  0.49993802,  0.20003099]])

In [89]:
np.allclose(nn.who, np.array([[ 0.37275328], [-0.03172939]]).T)

False

In [90]:
np.allclose(nn.wih,np.array([[ 0.10562014, -0.20185996], 
                              [0.39775194, 0.50074398], 
                              [-0.29887597, 0.19962801]]).T)

False

In [2]:
y = lambda x:max(0, x)
y(-9)

0

In [ ]:
import sys

sys.stdout.write("\rProgress: {:2.1f}".format(100 * ii/float(iterations)) \
                     + "% ... Training loss: " + str(train_loss)[:5] \
                     + " ... Validation loss: " + str(val_loss)[:5])
sys.stdout.flush()

### TensorFlow basic process (for mnist)

In [11]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data                                        # mnist data set
import numpy as np

In [12]:
import math

"""mini-batch"""
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    # TODO: Implement batching
    output_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        output_batches.append(batch)
        
    return output_batches

In [20]:
"""hyper-parameters define"""
batch_size = 128                                            # mini-batch size
epochs = 100                                                # epoch size
learn_rate = 0.1


"""data importation"""
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)
# The features are already scaled and the data is shuffled
train_features = mnist.train.images
valid_features = mnist.validation.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
valid_labels = mnist.validation.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# mini-batch operation
train_batches = batches(batch_size, train_features, train_labels)

"""model parameters define"""
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)


"""TensorFlow frame parameters define"""
# Features and Labels pre-define
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Logits is composed of weights and bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))           # weights
bias = tf.Variable(tf.random_normal([n_classes]))                       # bias
logits = tf.add(tf.matmul(features, weights), bias)                     # logis

# Learning  rate pre-define
learning_rate = tf.placeholder(tf.float32)

# Define loss by logits and labels
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
# Define optimizer by learning rate and loss
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy by 'equal', 'cast' and 'reduce_mean' functions
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

init = tf.global_variables_initializer()                    # globle variables pre-define

"""TensorFlow Session(main processing)"""
with tf.Session() as sess:
    sess.run(init)                                         # globle variables define

    # Training ALL data 'epoch' times
    for epoch_i in range(epochs):

        # Training data BATCH-by-BATCH a time
        for batch_features, batch_labels in train_batches:
            # re-define 'feed_dict' each time(used to transfer every batch of data included features and labels)
            train_feed_dict = {
                features: batch_features,
                labels: batch_labels,
                learning_rate: learn_rate}
            # run optimizer by 'feed_dict' to optimize model
            sess.run(optimizer, feed_dict=train_feed_dict)
            
        # Calculate loss by every batch of labels
        current_cost = sess.run(cost, feed_dict={features: batch_features, labels: batch_labels})

        # Calculate accuracy by validation data
        valid_accuracy = sess.run(accuracy, feed_dict={features: valid_features, labels: valid_labels})

        # epoch_i, sess, batch_features, batch_labels
        
        if epoch_i%10==0:
            print('Epoch: {:<4} - Cost: {:<8.3} Valid Accuracy: {:<5.3}'.format(
            epoch_i,
            current_cost,
            valid_accuracy))
        
    # Calculate accuracy for test dataset(target accuracy)
    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: test_features, labels: test_labels})
print('Test Accuracy: {}'.format(test_accuracy))

Extracting /datasets/ud730/mnist\train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-labels-idx1-ubyte.gz
Epoch: 0    - Cost: 1.7      Valid Accuracy: 0.741
Epoch: 10   - Cost: 0.629    Valid Accuracy: 0.878
Epoch: 20   - Cost: 0.509    Valid Accuracy: 0.893
Epoch: 30   - Cost: 0.444    Valid Accuracy: 0.899
Epoch: 40   - Cost: 0.402    Valid Accuracy: 0.902
Epoch: 50   - Cost: 0.372    Valid Accuracy: 0.905
Epoch: 60   - Cost: 0.349    Valid Accuracy: 0.908
Epoch: 70   - Cost: 0.331    Valid Accuracy: 0.91 
Epoch: 80   - Cost: 0.315    Valid Accuracy: 0.913
Epoch: 90   - Cost: 0.302    Valid Accuracy: 0.914
Test Accuracy: 0.9143000245094299
