In [1]:
text = 'As I was waiting, a man came out of a side room, and at a glance I was sure he must be Long John. \
His left leg was cut off close by the hip, and under the left shoulder he carried a crutch, which he managed \
with wonderful dexterity, hopping about upon it like a bird. He was very tall and strong, with a face as big \
as a ham—plain and pale, but intelligent and smiling. Indeed, he seemed in the most cheerful spirits, whistling \
as he moved about among the tables, with a merry word or a slap on the shoulder for the more favoured of his guests.'

In [3]:
text_low = text.lower()

In [4]:
text_low

'as i was waiting, a man came out of a side room, and at a glance i was sure he must be long john. his left leg was cut off close by the hip, and under the left shoulder he carried a crutch, which he managed with wonderful dexterity, hopping about upon it like a bird. he was very tall and strong, with a face as big as a ham—plain and pale, but intelligent and smiling. indeed, he seemed in the most cheerful spirits, whistling as he moved about among the tables, with a merry word or a slap on the shoulder for the more favoured of his guests.'

In [6]:
import re

s = re.compile('[a-zA-Z]*')
l = [i for i in s.findall(text_low) if len(i)]

In [26]:
l = [1,2,3,3,2,4]
d = dict()

In [27]:
help(d.get)

Help on built-in function get:

get(key, default=None, /) method of builtins.dict instance
    Return the value for key if key is in the dictionary, else default.



In [28]:
for n in l:
    d[n] = d.get(n, 0)+1

In [29]:
d

{1: 1, 2: 2, 3: 2, 4: 1}

In [4]:
import re

import requests
from bs4 import BeautifulSoup

def getUrlSpecifyText(url='https://cn.udacity.com/courses/all'):
    l = []
    
    req = requests.get(url)
    
    soup = BeautifulSoup(req.text, 'lxml')
    
    summaries = soup.find_all('div', class_='course-summary-card')
    for tag in summaries:
        l_sub = []
        
        l_sub.append(tag.select_one('h3 a').get_text().strip())          # 课程名称
        
        r = tag.find_all('span', 'ng-star-inserted')                     # 课程等级
        l_sub.append(r[0].get_text().strip())
        try:
            l_sub.append(r[1].get_text().strip())                        # 课程简介
        except IndexError as e:
            l_sub.append('None')                                         # 简介为空，则设为‘None’
            continue
             
        l.append(l_sub)
        
    return l

In [6]:
getUrlSpecifyText()[:10]

[['AI 产品经理 (英)', '初级', '驱动 AI 产品商业化落地，用 AI 为业务赋能，成为炙手可热稀缺人才。'],
 ['数据挖掘 求职直通班',
  '中级',
  '从数据分析、机器学习开始，掌握推荐系统和大数据计算框架 Spark 等核心技能，通过学习、项目、拓展、案例和求职辅导，系统完善对接职场需求，一站式直达职业目标'],
 ['市场营销分析 (英)',
  '初级',
  '掌握市场营销所需的基本数据技能，使用 Google Analytics 和 Data Studio 呈现你的结论'],
 ['传感器融合 (英)', '高级', '和梅赛德斯-奔驰学习，成为掌握无人驾驶、物联网、机器人开发核心技术的抢手工程师。'],
 ['数据洞察与说服技巧 (英)', '中级', '掌握数据可视化呈现商业洞察，练就用数据影响决策的说服技巧。'],
 ['云计算软件开发 (英)',
  '中级',
  '学习在 AWS 上构建全栈应用，并使用 Kubernetes 和 Serverless 框架分发采用微服务的应用，成为炙手可热的云计算软件开发工程师。'],
 ['云计算 DevOps (英)',
  '中级',
  '学习在 AWS 上通过代码部署基础设施和应用，构建 CI/CD 管道，以及使用 Kubernetes 和其他现代工具运维化微服务，成为一名抢手的云计算 DevOps 工程师。'],
 ['AI 求职直通班',
  '中级',
  '一站掌握机器学习、深度学习、CV、NLP 等 AI 核心技能，覆盖金融风控、计算机视觉、自然语言处理、数据挖掘、计算广告、语音识别六大热门领域，高性价比对接职场需求'],
 ['C++ 程序设计 (英)', '中级', '全面提升面向对象编程能力，成为 C++ 程序设计的专家。'],
 ['数据结构与算法 (英)', '中级', '精选 100+ 道面试真题，挑战数据结构与算法习题，获得详细项目审阅反馈，轻松应对求职面试和工作挑战。']]

In [7]:
s = """NLP is a way for computers to analyze, understand, and derive meaning from human language in a smart and useful way. 
By utilizing NLP, developers can organize and structure knowledge to perform tasks such as automatic summarization, translation, 
named entity recognition, relationship extraction, sentiment analysis, speech recognition, and topic segmentation.
“Apart from common word processor operations that treat text like a mere sequence of symbols, NLP considers the hierarchical 
structure of language: several words make a phrase, several phrases make a sentence and, ultimately, sentences convey ideas,” 
John Rehling, an NLP expert at Meltwater Group, said in How Natural Language Processing Helps Uncover Social Media Sentiment. 
“By analyzing language for its meaning, NLP systems have long filled useful roles, such as correcting grammar, converting speech 
to text and automatically translating between languages.”"""

In [9]:
import re 

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

def getNormalizedText(text=s):
    s_c = re.sub('[^a-zA-Z0-9]', ' ', text)
    
    # tokenize
    words = word_tokenize(s_c)
    
    # stopwords
    w_s = [w for w in words if w not in stopwords.words('english')]
    
    return w_s

In [10]:
getNormalizedText()[:10]

['NLP',
 'way',
 'computers',
 'analyze',
 'understand',
 'derive',
 'meaning',
 'human',
 'language',
 'smart']

### 句子解析

In [1]:
import nltk

#  nltk.ChartParser(my_grammar)

In [4]:
import nltk
from nltk.tokenize import word_tokenize

# Define a custom grammar
my_grammar = nltk.CFG.fromstring("""
S -> NP VP
PP -> P NP
NP -> Det N | Det N PP | 'I'
VP -> V NP | VP PP
Det -> 'an' | 'my'
N -> 'elephant' | 'pajamas'
V -> 'shot'
P -> 'in'
""")
parser = nltk.ChartParser(my_grammar)

# Parse a sentence
sentence = word_tokenize("I shot an elephant in my pajamas")
for tree in parser.parse(sentence):
    print(tree)

(S
  (NP I)
  (VP
    (VP (V shot) (NP (Det an) (N elephant)))
    (PP (P in) (NP (Det my) (N pajamas)))))
(S
  (NP I)
  (VP
    (V shot)
    (NP (Det an) (N elephant) (PP (P in) (NP (Det my) (N pajamas))))))


### 词干提取

In [6]:
from nltk.stem.porter import PorterStemmer

# Reduce words to their stems
stemmed = [PorterStemmer().stem(w) for w in words]
print(stemmed)

NameError: name 'words' is not defined

### 词形还原

In [7]:
from nltk.stem.wordnet import WordNetLemmatizer

# Reduce words to their root form
lemmed = [WordNetLemmatizer().lemmatize(w) for w in words]
print(lemmed)

NameError: name 'words' is not defined

In [ ]:
# Lemmatize verbs by specifying pos
lemmed = [WordNetLemmatizer().lemmatize(w, pos='v') for w in lemmed]
print(lemmed)

In [8]:
class NeuralNetwork(object):
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        # Initialize weights
        self.weights_input_to_hidden = np.random.normal(0.0, self.input_nodes**-0.5, 
                                       (self.input_nodes, self.hidden_nodes))

        self.weights_hidden_to_output = np.random.normal(0.0, self.hidden_nodes**-0.5, 
                                       (self.hidden_nodes, self.output_nodes))
        self.lr = learning_rate
        
        #### TODO: Set self.activation_function to your implemented sigmoid function ####
        #
        # Note: in Python, you can define a function with a lambda expression,
        # as shown below.
        self.activation_function = lambda x :  1 / (1+np.exp(-x))# Replace 0 with your sigmoid calculation.
        
        ### If the lambda code above is not something you're familiar with,
        # You can uncomment out the following three lines and put your 
        # implementation there instead.
        #
        #def sigmoid(x):
        #    return 0  # Replace 0 with your sigmoid calculation here
        #self.activation_function = sigmoid
                    
    
    def train(self, features, targets):
        ''' Train the network on batch of features and targets. 
        
            Arguments
            ---------
            
            features: 2D array, each row is one data record, each column is a feature
            targets: 1D array of target values
        
        '''
        n_records = features.shape[0]
        delta_weights_i_h = np.zeros(self.weights_input_to_hidden.shape)
        delta_weights_h_o = np.zeros(self.weights_hidden_to_output.shape)
        for X, y in zip(features, targets):
            #### Implement the forward pass here ####
            ### Forward pass ###
            # TODO: Hidden layer - Replace these values with your calculations.
            hidden_inputs = np.dot(X, self.weights_input_to_hidden) # signals into hidden layer
            hidden_outputs = self.activation_function(hidden_inputs) # signals from hidden layer

            # TODO: Output layer - Replace these values with your calculations.
            final_inputs = np.dot(hidden_outputs, self.weights_hidden_to_output) # signals into final output layer
            final_outputs = self.activation_function(final_inputs) # signals from final output layer
            
            #### Implement the backward pass here ####
            ### Backward pass ###

            # TODO: Output error - Replace this value with your calculations.
            error = y - final_outputs # Output layer error is the difference between desired target and actual output.
            # error_term = error * final_outputs * (1-final_outputs)
            
            # TODO: Calculate the hidden layer's contribution to the error
            hidden_error = np.dot(error * final_outputs * (1-final_outputs), final_inputs)
            # hidden_error_term = hidden_error * hidden_outputs * (1-hidden_outputs)
            
            # TODO: Backpropagated error terms - Replace these values with your calculations.
            output_error_term = error * final_outputs * (1-final_outputs)
            hidden_error_term = hidden_error * hidden_outputs * (1-hidden_outputs)

            # Weight step (input to hidden)
            delta_weights_i_h += hidden_error_term * X[:, None]
            # Weight step (hidden to output)
            delta_weights_h_o += (output_error_term * hidden_outputs)[:, None]

        # TODO: Update the weights - Replace these values with your calculations.
        self.weights_hidden_to_output += self.lr * delta_weights_h_o / n_records # update hidden-to-output weights with gradient descent step
        self.weights_input_to_hidden += self.lr * delta_weights_i_h / n_records # update input-to-hidden weights with gradient descent step
 
    def run(self, features):
        ''' Run a forward pass through the network with input features 
        
            Arguments
            ---------
            features: 1D array of feature values
        '''
        
        #### Implement the forward pass here ####
        # TODO: Hidden layer - replace these values with the appropriate calculations.
        hidden_inputs =  np.dot(features, self.weights_input_to_hidden) # signals into hidden layer
        hidden_outputs = self.activation_function(hidden_inputs) # signals from hidden layer
        
        # TODO: Output layer - Replace these values with the appropriate calculations.
        final_inputs = np.dot(hidden_outputs, self.weights_hidden_to_output) # signals into final output layer
        final_outputs = self.activation_function(final_inputs) # signals from final output layer 
        
        return final_outputs

In [9]:
import numpy as np
inputs = np.array([[0.5, -0.2, 0.1]])
targets = np.array([[0.4]])

In [11]:
(np.array([-0.03116616]) * np.array([0.4850045,0.45512111]))

array([-0.01511573, -0.01418438])

In [15]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

In [18]:
np.allclose([1e10,1e-8], [1e10,1e-9])

True

### nn

In [62]:
import numpy
import scipy.special

In [104]:
class neuralNetwork:
    # 初始化神经网络（各层节点数、学习率） --各层节点数、学习率、2个权重矩阵、激活函数
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 输入层、隐藏层、输出层的节点数量
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # 学习率
        self.lr = learningrate
        
        ## 权重矩阵（一列）  --numpy.random.normal
        # 权重数组中的w_i_j，表示链接是从下一层的节点i到节点j --使用正态分布采样权重
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 设置激活函数S -scipy.special.expit(x)
        self.activation_function = lambda x: 1/(1+numpy.exp(-x))
        
        pass
    
    # 训练神经网络（训练数据集整理后的输入列表，目标数值列表） --train数据集输入，训练神经网络，调整权重
    def train(self, inputs_list, targets_list):
        # 将输入列表转换为二维数组并转置
        # 将目标列表转换为二维数组并转置
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        
        # 矩阵点乘法--计算进入隐藏层的信号
        # 激活函数--计算离开隐藏层的信号
        hidden_inputs = numpy.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # 矩阵点乘法--计算进入最终输出层的信号
        # 激活函数--计算离开最终输出层的信号（最终输出）
        final_inputs = numpy.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        print('final_outputs', final_outputs)
        
        # 隐蔽层和最终层的误差
        # 输入层和隐藏层的误差
        print('targets', targets)
        output_errors = targets - final_outputs
        print('output_errors', output_errors)
        hidden_errors = numpy.dot(self.who.T, output_errors) 
        print('hidden_errors', hidden_errors)
        
        # 为隐藏层和最终层间权重矩阵进行更新
        # 为输入层和隐藏层间权重矩阵进行更新
        print('who_term', (output_errors * final_outputs * (1.0 - final_outputs)))
        print('wih_term', (hidden_errors * hidden_outputs * (1.0 - hidden_outputs)))
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        
        
    # 查询神经网络（测试数据集整理后的输入列表） --训练后，test数据集输入，返回计算得出的检验样本集最终输出
    def query(self, inputs_list):
        # 将输入列表转换为二维数组并转置
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # 矩阵点乘法--计算进入隐藏层的信号
        # 激活函数--计算离开隐藏层的信号
        hidden_inputs = numpy.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # 矩阵点乘法--计算进入最终输出层的信号
        # 激活函数--计算离开最终输出层的信号（最终输出）
        final_inputs = numpy.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        # 返回最终输出列表
        return final_outputs
    
        pass

In [105]:
x = np.arange(4).reshape((2,2))

x

array([[0, 1],
       [2, 3]])

In [106]:
numpy.transpose(x)

array([[0, 2],
       [1, 3]])

In [107]:
x.T

array([[0, 2],
       [1, 3]])

#### nn-data

In [109]:
import numpy as np
x = np.array([[0.5, -0.2, 0.1]])
target = np.array([[0.4]])
learnrate = 0.5

# 3*2
weights_input_hidden = np.array([[0.1, -0.2],
                                 [0.4, 0.5],
                                 [-0.3, 0.2]]).T
# 2*1
weights_hidden_output = np.array([[0.3],
                                  [-0.1]]).T

delta_weights_i_h = np.zeros(weights_input_hidden.shape)
delta_weights_h_o = np.zeros(weights_hidden_output.shape)

In [110]:
weights_input_hidden, weights_hidden_output

(array([[ 0.1,  0.4, -0.3],
        [-0.2,  0.5,  0.2]]), array([[ 0.3, -0.1]]))

#### 实例化（测试train）

In [111]:
nn = neuralNetwork(3,2,1,0.1)

nn.wih = weights_input_hidden.copy()
nn.who = weights_hidden_output.copy()

In [112]:
# 转为list of list
X = list(x[0])
y = list(target[0])

X, y

([0.5, -0.2, 0.1], [0.4])

In [113]:
nn.train(x, target)

final_outputs [[0.5249765]]
targets [[0.4]]
output_errors [[-0.1249765]]
hidden_errors [[-0.03749295]
 [ 0.01249765]]
who_term [[-0.03116616]]
wih_term [[-0.00936481]
 [ 0.00309924]]


In [87]:
nn.who

array([[ 0.29848843, -0.10141844]])

In [88]:
nn.wih

array([[ 0.09953176,  0.4001873 , -0.30009365],
       [-0.19984504,  0.49993802,  0.20003099]])

In [89]:
np.allclose(nn.who, np.array([[ 0.37275328], [-0.03172939]]).T)

False

In [90]:
np.allclose(nn.wih,np.array([[ 0.10562014, -0.20185996], 
                              [0.39775194, 0.50074398], 
                              [-0.29887597, 0.19962801]]).T)

False

In [2]:
y = lambda x:max(0, x)
y(-9)

0