## Target

- __`notMNIST`__数据集：由 A 到 J 的英文字母图片组成的数据集。

<img src="./notMNIST.jpg" width=360px>

`根据数据集中的图片，自动识别字母`

## easy test

In [3]:
import tensorflow as tf

In [11]:
hello_constant = tf.constant(r'Hello World!')              # 0 维度的字符串 tensor（常量）

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


### tensor（不同大小）

In [12]:
hello_constant = tf.constant(r'Hello World!')              # 0 维度的字符串 tensor（常量）

In [13]:
# A is a 0-dimensional int32 tensor
A = tf.constant(1234) 
# B is a 1-dimensional int32 tensor
B = tf.constant([123,456,789]) 
 # C is a 2-dimensional int32 tensor
C = tf.constant([ [123,456,789], [222,333,444] ])

### Session（内里可对 tensor 求值）

In [14]:
with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


In [15]:
with tf.Session() as sess:
    outputA = sess.run(A)
    outputB = sess.run(B)
    outputC = sess.run(C)
    
    print(outputA)
    print(outputB)
    print(outputC)

1234
[123 456 789]
[[123 456 789]
 [222 333 444]]


## 输入

- tf.placeholder()
- feed_dict属性

In [17]:
# single value for single parameter
x = tf.placeholder(tf.string)                                # placeholder, define parameter type

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello World'})       # feed_dict parameter, assignment
    print(output)

Hello World


In [28]:
# multi values for multi parameters
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    outputx = sess.run(x, feed_dict={x: 'Test String', y: 123, z: 45.67})
    outputy = sess.run(y, feed_dict={y: 999, z: 45.67})                                 # 减少一个dict值，并改变赋值
    outputz = sess.run((x,y,z), feed_dict={x: 'Test String', y: 123, z: 45.67})         # 运行多个取值
    
    print(outputx)
    print(outputy)
    print(outputz)

Test String
999
(array('Test String', dtype=object), array(123), array(45.67, dtype=float32))


In [22]:
def run():
    output = None
    x = tf.placeholder(tf.int32)

    with tf.Session() as sess:
        # TODO: Feed the x tensor 123
        output = sess.run(x, feed_dict={x:123})

    return output

run()

array(123)

## 数学运算

In [32]:
x = tf.add(5, 2)                 # addition, result is 7

with tf.Session() as sess:
    output = sess.run(x)
    print(output)

7


In [33]:
x = tf.subtract(10, 4)          # subtraction,result is 6
y = tf.multiply(2, 5)           # multiplication, result is 10

with tf.Session() as sess:
    output = sess.run((x,y))
    print(output)

(6, 10)


In [35]:
# Fails with ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 
# tf.subtract(tf.constant(2.0),tf.constant(1))  
tf.subtract(tf.constant(2.0),tf.constant(1.0))  

<tf.Tensor 'Sub_2:0' shape=() dtype=float32>