## Target

- __`notMNIST`__数据集：由 A 到 J 的英文字母图片组成的数据集。

<img src="./notMNIST.jpg" width=360px>

`根据数据集中的图片，自动识别字母`

## easy test

In [3]:
import tensorflow as tf

In [4]:
hello_constant = tf.constant(r'Hello World!')              # 0 维度的字符串 tensor（常量）

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


### tensor（不同大小）

In [4]:
hello_constant = tf.constant(r'Hello World!')              # 0 维度的字符串 tensor（常量）

In [5]:
# A is a 0-dimensional int32 tensor
A = tf.constant(1234) 
# B is a 1-dimensional int32 tensor
B = tf.constant([123,456,789]) 
 # C is a 2-dimensional int32 tensor
C = tf.constant([ [123,456,789], [222,333,444] ])

### Session（内里可对 tensor 求值）

In [6]:
with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


In [7]:
with tf.Session() as sess:
    outputA = sess.run(A)
    outputB = sess.run(B)
    outputC = sess.run(C)
    
    print(outputA)
    print(outputB)
    print(outputC)

1234
[123 456 789]
[[123 456 789]
 [222 333 444]]


## 输入

- tf.placeholder()
- feed_dict属性

In [8]:
# single value for single parameter
x = tf.placeholder(tf.string)                                # placeholder, define parameter type

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello World'})       # feed_dict parameter, assignment
    print(output)

Hello World


In [9]:
# multi values for multi parameters
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    outputx = sess.run(x, feed_dict={x: 'Test String', y: 123, z: 45.67})
    outputy = sess.run(y, feed_dict={y: 999, z: 45.67})                                 # 减少一个dict值，并改变赋值
    outputz = sess.run((x,y,z), feed_dict={x: 'Test String', y: 123, z: 45.67})         # 运行多个取值
    
    print(outputx)
    print(outputy)
    print(outputz)

Test String
999
(array('Test String', dtype=object), array(123), array(45.67, dtype=float32))


In [10]:
def run():
    output = None
    x = tf.placeholder(tf.int32)

    with tf.Session() as sess:
        # TODO: Feed the x tensor 123
        output = sess.run(x, feed_dict={x:123})

    return output

run()

array(123)

## 数学运算

In [11]:
x = tf.add(5, 2)                 # addition, result is 7

with tf.Session() as sess:
    output = sess.run(x)
    print(output)

7


In [12]:
x = tf.subtract(10, 4)          # subtraction,result is 6
y = tf.multiply(2, 5)           # multiplication, result is 10
z = tf.divide(tf.constant(9), tf.constant(3))    # division, result is 3.0

with tf.Session() as sess:
    output = sess.run((x,y,z))
    print(output)

(6, 10, 3.0)


### 类型转换

In [13]:
# Fails with ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 
# tf.subtract(tf.constant(2.0),tf.constant(1))  

x = tf.subtract(tf.constant(2.0),tf.constant(1.0))
y = tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))   # tranform, result is 1

with tf.Session() as sess:
    output = sess.run((x,y))
    print(output)

(1.0, 1)


### 练习

In [14]:
x = 10
y = 2
z = x/y - 1

# TODO: Print z from a session
with tf.Session() as sess:
    output = sess.run(tf.cast(tf.constant(z), tf.float64))
    print(output)

4.0


In [15]:
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x,y),tf.cast(tf.constant(1), tf.float64))

# TODO: Print z from a session
with tf.Session() as sess:
    output = sess.run(z)
    print(output)

4.0


## 线性函数

In [22]:
x = tf.Variable(5)                               # initialize ONE variable
init = tf.global_variables_initializer()         # initialize ALL variables

with tf.Session() as sess:
    sess.run(init)
    output = sess.run(x)
    print(output)

5


### 随机权重

In [20]:
n_features = 120
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels))) # initialize weight with a RANDOM number from normal distribution

weights

<tf.Variable 'Variable_3:0' shape=(120, 5) dtype=float32_ref>

### 零偏差

In [26]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))                           # initialize bias with ZERO

### mnist练习

1.打开 quiz.py
    1.实现 get_weights 让它返回一个权重的 tf.Variable
    2. 实现 get_biases 返回一个偏差的 tf.Variable
    3.在 linear 函数中实现 xW + b
2.打开 sandbox.py
    1. 初始化权重
    2.因为 xW + b 中的 xW 是矩阵相乘，所以你要用 `tf.matmul()` 函数，而不是 `tf.multiply()`。不要忘记矩阵相乘的规则，tf.matmul(a,b) 不等于tf.matmul(b,a)。

In [14]:
'''quiz.py'''
# return a 'tf.Variable' stand for weights
def get_weights(n_features, n_labels):
    """
    Return TensorFlow weights
    :param n_features: Number of features
    :param n_labels: Number of labels
    :return: TensorFlow weights
    """
    # TODO: Return weights
    return tf.Variable(tf.truncated_normal((n_features, n_labels)))

# return a 'tf.Variable' stand for bias
def get_biases(n_labels):
    """
    Return TensorFlow bias
    :param n_labels: Number of labels
    :return: TensorFlow bias
    """
    # TODO: Return biases
    return tf.Variable(tf.zeros(n_labels))

# formula: y = xW + b
def linear(inputs, w, b):
    """
    Return linear function in TensorFlow
    :param input: TensorFlow input
    :param w: TensorFlow weights
    :param b: TensorFlow biases
    :return: TensorFlow linear function
    """
    # TODO: Linear Function (xW + b)
    return tf.add(tf.matmul(inputs, w), b)                    # loss: 4.2149
#     return inputs@w+b                                         # loss: 8.2723

In [15]:
'''sandbox.py'''
from tensorflow.examples.tutorials.mnist import input_data                           # MNIST data set

def mnist_features_labels(n_labels):
    """
    Gets the first <n> labels from the MNIST dataset
    :param n_labels: Number of labels to use
    :return: Tuple of feature list and label list
    """
    mnist_features = []                                                              # MNIST features names
    mnist_labels = []                                                               # MNIST labels names

    mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)        # one-hot coding for MNIST

    '''In order to make quizzes run faster, we're only looking at 10000 images'''
    for mnist_feature, mnist_label in zip(*mnist.train.next_batch(10000)):          
        # Add features and labels if it's for the first <n>th labels
        if mnist_label[:n_labels].any():
            mnist_features.append(mnist_feature)
            mnist_labels.append(mnist_label[:n_labels])

    return mnist_features, mnist_labels


# Number of features (28*28 image is 784 features)
n_features = 784
# Number of labels
n_labels = 3

# Features and Labels(define dtypes of featrues and labels)
features = tf.placeholder(tf.float32)
labels = tf.placeholder(tf.float32)

# Weights and Biases
w = get_weights(n_features, n_labels)
b = get_biases(n_labels)

# Linear Function xW + b
logits = linear(features, w, b)

# Training data
train_features, train_labels = mnist_features_labels(n_labels)

with tf.Session() as session:
    # TODO: Initialize session variables
    session.run(tf.global_variables_initializer()) # initialize ALL variable and run 
    
    # Softmax
    prediction = tf.nn.softmax(logits)

    # Cross entropy
    # This quantifies how far off the predictions were.
    # You'll learn more about this in future lessons.
    cross_entropy = -tf.reduce_sum(labels * tf.log(prediction), reduction_indices=1)

    # Training loss
    # You'll learn more about this in future lessons.
    loss = tf.reduce_mean(cross_entropy)

    # Rate at which the weights are changed
    # You'll learn more about this in future lessons.
    learning_rate = 0.08

    # Gradient Descent
    # This is the method used to train the model
    # You'll learn more about this in future lessons.
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

    # Run optimizer and get loss
    _, l = session.run(
        [optimizer, loss],
        feed_dict={features: train_features, labels: train_labels})

# Print loss
print('Loss: {}'.format(l))


Extracting /datasets/ud730/mnist\train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-labels-idx1-ubyte.gz
Loss: 8.272327423095703


## TensorFlow Softmax

In [17]:
x = tf.nn.softmax([2.0, 1.0, 0.2])

with tf.Session() as sess:
    output = sess.run(x)
    print(output)

[0.65223986 0.23994564 0.10781453]


In [44]:
x = tf.nn.softmax([2.0, 1.0, -1.0])

with tf.Session() as sess:
    output = sess.run(x)
    print(output)

[0.70538455 0.25949648 0.03511903]


### 练习

In [19]:
def run():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)
    
    # TODO: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logit_data)
    
    with tf.Session() as sess:
        # TODO: Feed in the logit data
#         output = sess.run(softmax, feed_dict={logits: logit_data})
        output = sess.run(softmax)

    return output

run()

array([0.6590012 , 0.24243298, 0.09856589], dtype=float32)

## 交叉熵

In [24]:
x = tf.reduce_sum([1, 2, 3, 4, 5])  # calculate the sum of a sequences, result is 15
y = tf.log(100.0)                     # calculate the log of num, result is 4.60517

with tf.Session() as sess:
    output = sess.run((x, y))
    print(output)

(15, 4.6051702)


### 练习

In [42]:
softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# TODO: Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

with tf.Session() as sess:
    print(sess.run(cross_entropy, feed_dict={softmax: softmax_data, one_hot: one_hot_data}))

0.35667497


In [43]:
softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# TODO: Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot_data, tf.log(softmax_data)))

with tf.Session() as sess:
    print(sess.run(cross_entropy))

0.35667497


## mini-batch

- 减少运算内存，避免内存要求过大

In [45]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf

In [47]:
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

weights, bias

Extracting /datasets/ud730/mnist\train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-labels-idx1-ubyte.gz


(<tf.Variable 'Variable_12:0' shape=(784, 10) dtype=float32_ref>,
 <tf.Variable 'Variable_13:0' shape=(10,) dtype=float32_ref>)

| name | shape | type | memory_space |
| --- | --- | --- | --- |
| train_features | Shape: (55000, 784) | Type: float32 | 172480000 | 
| train_labels | Shape: (55000, 10) | Type: float32 | 2200000 | 
| weights | Shape: (784, 10) | Type: float32 | 31360 | 
| bias | Shape: (10,) | Type: float32 | 40 | 

Total:`174MB`

### 把数据集分成 batch

In [ ]:
n_input = 784                       # nums of inputs features
n_classes = 10                      # nums of probable output classes

# (variable size)Features and Labels
# ('None' dimension:a placeholder with batch size)
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

### 实现mini-batch

In [10]:
# import math

# def batches(batch_size, features, labels):
#     """
#     Create batches of features and labels
#     :param batch_size: The batch size
#     :param features: List of features
#     :param labels: List of labels
#     :return: Batches of (Features, Labels)
#     """
#     assert len(features) == len(labels)
#     # TODO: Implement batching
#     l_t = []
#     n_b = len(features)//batch_size
#     for i in range(n_b):
#         l_t.append([features[batch_size*i:batch_size*(i+1)], labels[batch_size*i:batch_size*(i+1)]])
#     l_t.append([features[batch_size*n_b:], labels[batch_size*n_b:]])
    
#     return l_t

In [15]:
import math
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    # TODO: Implement batching
    output_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        output_batches.append(batch)
        
    return output_batches

In [16]:
from pprint import pprint

'''对 features 和 labels 实现一个 batches 函数。这个函数返回每个有最大 batch_size 数据点的 batch。'''
# 4 Samples of features
example_features = [
    ['F11','F12','F13','F14'],
    ['F21','F22','F23','F24'],
    ['F31','F32','F33','F34'],
    ['F41','F42','F43','F44']]
# 4 Samples of labels
example_labels = [
    ['L11','L12'],
    ['L21','L22'],
    ['L31','L32'],
    ['L41','L42']]

# PPrint prints data structures like 2d arrays, so they are easier to read
pprint(batches(3, example_features, example_labels))

[[[['F11', 'F12', 'F13', 'F14'],
   ['F21', 'F22', 'F23', 'F24'],
   ['F31', 'F32', 'F33', 'F34']],
  [['L11', 'L12'], ['L21', 'L22'], ['L31', 'L32']]],
 [[['F41', 'F42', 'F43', 'F44']], [['L41', 'L42']]]]


`example_batches` 变量如下：
```python
[
    # 分 2 个 batch:
    #   第一个 batch 的 size 是 3
    #   第二个 batch 的 size 是 1
    [
        # size 为 3 的第一个 Batch
        [
            # 3 个特征样本
            # 每个样本有四个特征
            ['F11', 'F12', 'F13', 'F14'],
            ['F21', 'F22', 'F23', 'F24'],
            ['F31', 'F32', 'F33', 'F34']
        ], [
            # 3 个标签样本
            # 每个标签有两个 label
            ['L11', 'L12'],
            ['L21', 'L22'],
            ['L31', 'L32']
        ]
    ], [
        # size 为 1 的第二个 Batch 
        # 因为 batch size 是 3。所以四个样品中只有一个在这里。
        [
            # 1 一个样本特征
            ['F41', 'F42', 'F43', 'F44']
        ], [
            # 1 个 label
            ['L41', 'L42']
        ]
    ]
]
```

### mnist练习

In [19]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
import numpy as np

learning_rate = 0.001
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer(using logits curve)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))


# TODO: Set batch size
batch_size = 128
assert batch_size is not None, 'You must set the batch size'

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    # TODO: Train optimizer on all batches
    # for batch_features, batch_labels in ______
    for batch_features, batch_labels in batches(batch_size, train_features, train_labels):
        sess.run(optimizer, feed_dict={features: batch_features, labels: batch_labels})

    # Calculate accuracy for test dataset
    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))

Extracting /datasets/ud730/mnist\train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-labels-idx1-ubyte.gz
Test Accuracy: 0.10540000349283218


__END__      
1.`2019.07.26`