## Target

- __`notMNIST`__数据集：由 A 到 J 的英文字母图片组成的数据集。

<img src="./notMNIST.jpg" width=360px>

`根据数据集中的图片，自动识别字母`

## easy test

In [2]:
import tensorflow as tf

In [2]:
hello_constant = tf.constant(r'Hello World!')              # 0 维度的字符串 tensor（常量）

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


### tensor（不同大小）

In [3]:
hello_constant = tf.constant(r'Hello World!')              # 0 维度的字符串 tensor（常量）

In [4]:
# A is a 0-dimensional int32 tensor
A = tf.constant(1234) 
# B is a 1-dimensional int32 tensor
B = tf.constant([123,456,789]) 
 # C is a 2-dimensional int32 tensor
C = tf.constant([ [123,456,789], [222,333,444] ])

### Session（内里可对 tensor 求值）

In [5]:
with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


In [6]:
with tf.Session() as sess:
    outputA = sess.run(A)
    outputB = sess.run(B)
    outputC = sess.run(C)
    
    print(outputA)
    print(outputB)
    print(outputC)

1234
[123 456 789]
[[123 456 789]
 [222 333 444]]


## 输入

- tf.placeholder()
- feed_dict属性

In [7]:
# single value for single parameter
x = tf.placeholder(tf.string)                                # placeholder, define parameter type

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello World'})       # feed_dict parameter, assignment
    print(output)

Hello World


In [8]:
# multi values for multi parameters
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    outputx = sess.run(x, feed_dict={x: 'Test String', y: 123, z: 45.67})
    outputy = sess.run(y, feed_dict={y: 999, z: 45.67})                                 # 减少一个dict值，并改变赋值
    outputz = sess.run((x,y,z), feed_dict={x: 'Test String', y: 123, z: 45.67})         # 运行多个取值
    
    print(outputx)
    print(outputy)
    print(outputz)

Test String
999
(array('Test String', dtype=object), array(123), array(45.67, dtype=float32))


In [9]:
def run():
    output = None
    x = tf.placeholder(tf.int32)

    with tf.Session() as sess:
        # TODO: Feed the x tensor 123
        output = sess.run(x, feed_dict={x:123})

    return output

run()

array(123)

## 数学运算

In [10]:
x = tf.add(5, 2)                 # addition, result is 7

with tf.Session() as sess:
    output = sess.run(x)
    print(output)

7


In [11]:
x = tf.subtract(10, 4)          # subtraction,result is 6
y = tf.multiply(2, 5)           # multiplication, result is 10
z = tf.divide(tf.constant(9), tf.constant(3))    # division, result is 3.0

with tf.Session() as sess:
    output = sess.run((x,y,z))
    print(output)

(6, 10, 3.0)


### 类型转换

In [12]:
# Fails with ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 
# tf.subtract(tf.constant(2.0),tf.constant(1))  

x = tf.subtract(tf.constant(2.0),tf.constant(1.0))
y = tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))   # tranform, result is 1

with tf.Session() as sess:
    output = sess.run((x,y))
    print(output)

(1.0, 1)


### 练习

In [13]:
x = 10
y = 2
z = x/y - 1

# TODO: Print z from a session
with tf.Session() as sess:
    output = sess.run(tf.cast(tf.constant(z), tf.float64))
    print(output)

4.0


In [14]:
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x,y),tf.cast(tf.constant(1), tf.float64))

# TODO: Print z from a session
with tf.Session() as sess:
    output = sess.run(z)
    print(output)

4.0


## 线性函数

In [15]:
x = tf.Variable(5)                               # initialize ONE variable
init = tf.global_variables_initializer()         # initialize ALL variables

with tf.Session() as sess:
    sess.run(init)
    output = sess.run(x)
    print(output)

Instructions for updating:
Colocations handled automatically by placer.
5


### 随机权重

In [16]:
n_features = 120
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels))) # initialize weight with a RANDOM number from normal distribution

weights

<tf.Variable 'Variable_1:0' shape=(120, 5) dtype=float32_ref>

### 零偏差

In [17]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))                           # initialize bias with ZERO

### mnist练习

1.打开 quiz.py
    1.实现 get_weights 让它返回一个权重的 tf.Variable
    2. 实现 get_biases 返回一个偏差的 tf.Variable
    3.在 linear 函数中实现 xW + b
2.打开 sandbox.py
    1. 初始化权重
    2.因为 xW + b 中的 xW 是矩阵相乘，所以你要用 `tf.matmul()` 函数，而不是 `tf.multiply()`。不要忘记矩阵相乘的规则，tf.matmul(a,b) 不等于tf.matmul(b,a)。

In [18]:
'''quiz.py'''
# return a 'tf.Variable' stand for weights
def get_weights(n_features, n_labels):
    """
    Return TensorFlow weights
    :param n_features: Number of features
    :param n_labels: Number of labels
    :return: TensorFlow weights
    """
    # TODO: Return weights
    return tf.Variable(tf.truncated_normal((n_features, n_labels)))

# return a 'tf.Variable' stand for bias
def get_biases(n_labels):
    """
    Return TensorFlow bias
    :param n_labels: Number of labels
    :return: TensorFlow bias
    """
    # TODO: Return biases
    return tf.Variable(tf.zeros(n_labels))

# formula: y = xW + b
def linear(inputs, w, b):
    """
    Return linear function in TensorFlow
    :param input: TensorFlow input
    :param w: TensorFlow weights
    :param b: TensorFlow biases
    :return: TensorFlow linear function
    """
    # TODO: Linear Function (xW + b)
    return tf.add(tf.matmul(inputs, w), b)                    # loss: 4.2149
#     return inputs@w+b                                         # loss: 8.2723

In [19]:
'''sandbox.py'''
from tensorflow.examples.tutorials.mnist import input_data                           # MNIST data set

def mnist_features_labels(n_labels):
    """
    Gets the first <n> labels from the MNIST dataset
    :param n_labels: Number of labels to use
    :return: Tuple of feature list and label list
    """
    mnist_features = []                                                              # MNIST features names
    mnist_labels = []                                                               # MNIST labels names

    mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)        # one-hot coding for MNIST

    '''In order to make quizzes run faster, we're only looking at 10000 images'''
    for mnist_feature, mnist_label in zip(*mnist.train.next_batch(10000)):          
        # Add features and labels if it's for the first <n>th labels
        if mnist_label[:n_labels].any():
            mnist_features.append(mnist_feature)
            mnist_labels.append(mnist_label[:n_labels])

    return mnist_features, mnist_labels


# Number of features (28*28 image is 784 features)
n_features = 784
# Number of labels
n_labels = 3

# Features and Labels(define dtypes of featrues and labels)
features = tf.placeholder(tf.float32)
labels = tf.placeholder(tf.float32)

# Weights and Biases
w = get_weights(n_features, n_labels)
b = get_biases(n_labels)

# Linear Function xW + b
logits = linear(features, w, b)

# Training data
train_features, train_labels = mnist_features_labels(n_labels)

with tf.Session() as session:
    # TODO: Initialize session variables
    session.run(tf.global_variables_initializer()) # initialize ALL variable and run 
    
    # Softmax
    prediction = tf.nn.softmax(logits)

    # Cross entropy
    # This quantifies how far off the predictions were.
    # You'll learn more about this in future lessons.
    cross_entropy = -tf.reduce_sum(labels * tf.log(prediction), reduction_indices=1)

    # Training loss
    # You'll learn more about this in future lessons.
    loss = tf.reduce_mean(cross_entropy)

    # Rate at which the weights are changed
    # You'll learn more about this in future lessons.
    learning_rate = 0.08

    # Gradient Descent
    # This is the method used to train the model
    # You'll learn more about this in future lessons.
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

    # Run optimizer and get loss
    _, l = session.run(
        [optimizer, loss],
        feed_dict={features: train_features, labels: train_labels})

# Print loss
print('Loss: {}'.format(l))


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /datasets/ud730/mnist\train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /datasets/ud730/mnist\train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting /datasets/ud730/mnist\t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Use tf.cast instead.
Loss: 5.999691009521484


## TensorFlow Softmax

In [20]:
x = tf.nn.softmax([2.0, 1.0, 0.2])

with tf.Session() as sess:
    output = sess.run(x)
    print(output)

[0.65223986 0.23994564 0.10781453]


In [21]:
x = tf.nn.softmax([2.0, 1.0, -1.0])

with tf.Session() as sess:
    output = sess.run(x)
    print(output)

[0.70538455 0.25949648 0.03511903]


### 练习

In [22]:
def run():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)
    
    # TODO: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logit_data)
    
    with tf.Session() as sess:
        # TODO: Feed in the logit data
#         output = sess.run(softmax, feed_dict={logits: logit_data})
        output = sess.run(softmax)

    return output

run()

array([0.6590012 , 0.24243298, 0.09856589], dtype=float32)

## 交叉熵

In [3]:
import numpy as np
x = tf.reduce_sum([1, 2, 3, 4, 5])  # calculate the sum of a sequences, result is 15
y = tf.log(np.exp(3))                     # calculate the log of num, result is 4.60517

with tf.Session() as sess:
    output = sess.run((x, y))
    print(output)

(15, 3.0)


### 练习

In [ ]:
# softmax_data = [0.7, 0.2, 0.1]
# one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# TODO: Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

with tf.Session() as sess:
    print(sess.run(cross_entropy, feed_dict={softmax: softmax_data, one_hot: one_hot_data}))

In [25]:
softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# TODO: Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot_data, tf.log(softmax_data)))

with tf.Session() as sess:
    print(sess.run(cross_entropy))

0.35667497


## mini-batch

- 减少运算内存，避免内存要求过大

In [28]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
import numpy as np

In [29]:
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

weights, bias

Extracting /datasets/ud730/mnist\train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-labels-idx1-ubyte.gz


(<tf.Variable 'Variable_5:0' shape=(784, 10) dtype=float32_ref>,
 <tf.Variable 'Variable_6:0' shape=(10,) dtype=float32_ref>)

| name | shape | type | memory_space |
| --- | --- | --- | --- |
| train_features | Shape: (55000, 784) | Type: float32 | 172480000 | 
| train_labels | Shape: (55000, 10) | Type: float32 | 2200000 | 
| weights | Shape: (784, 10) | Type: float32 | 31360 | 
| bias | Shape: (10,) | Type: float32 | 40 | 

Total:`174MB`

### 把数据集分成 batch

In [30]:
n_input = 784                       # nums of inputs features
n_classes = 10                      # nums of probable output classes

# (variable size)Features and Labels
# ('None' dimension:a placeholder with batch size)
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

### 实现mini-batch

In [31]:
# import math

# def batches(batch_size, features, labels):
#     """
#     Create batches of features and labels
#     :param batch_size: The batch size
#     :param features: List of features
#     :param labels: List of labels
#     :return: Batches of (Features, Labels)
#     """
#     assert len(features) == len(labels)
#     # TODO: Implement batching
#     l_t = []
#     n_b = len(features)//batch_size
#     for i in range(n_b):
#         l_t.append([features[batch_size*i:batch_size*(i+1)], labels[batch_size*i:batch_size*(i+1)]])
#     l_t.append([features[batch_size*n_b:], labels[batch_size*n_b:]])
    
#     return l_t

In [32]:
import math
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    # TODO: Implement batching
    output_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        output_batches.append(batch)
        
    return output_batches

In [33]:
from pprint import pprint

'''对 features 和 labels 实现一个 batches 函数。这个函数返回每个有最大 batch_size 数据点的 batch。'''
# 4 Samples of features
example_features = [
    ['F11','F12','F13','F14'],
    ['F21','F22','F23','F24'],
    ['F31','F32','F33','F34'],
    ['F41','F42','F43','F44']]
# 4 Samples of labels
example_labels = [
    ['L11','L12'],
    ['L21','L22'],
    ['L31','L32'],
    ['L41','L42']]

# PPrint prints data structures like 2d arrays, so they are easier to read
pprint(batches(3, example_features, example_labels))

[[[['F11', 'F12', 'F13', 'F14'],
   ['F21', 'F22', 'F23', 'F24'],
   ['F31', 'F32', 'F33', 'F34']],
  [['L11', 'L12'], ['L21', 'L22'], ['L31', 'L32']]],
 [[['F41', 'F42', 'F43', 'F44']], [['L41', 'L42']]]]


`example_batches` 变量如下：
```python
[
    # 分 2 个 batch:
    #   第一个 batch 的 size 是 3
    #   第二个 batch 的 size 是 1
    [
        # size 为 3 的第一个 Batch
        [
            # 3 个特征样本
            # 每个样本有四个特征
            ['F11', 'F12', 'F13', 'F14'],
            ['F21', 'F22', 'F23', 'F24'],
            ['F31', 'F32', 'F33', 'F34']
        ], [
            # 3 个标签样本
            # 每个标签有两个 label
            ['L11', 'L12'],
            ['L21', 'L22'],
            ['L31', 'L32']
        ]
    ], [
        # size 为 1 的第二个 Batch 
        # 因为 batch size 是 3。所以四个样品中只有一个在这里。
        [
            # 1 一个样本特征
            ['F41', 'F42', 'F43', 'F44']
        ], [
            # 1 个 label
            ['L41', 'L42']
        ]
    ]
]
```

### mnist练习

In [34]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
import numpy as np

learning_rate = 0.001
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer(using logits curve)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))


# TODO: Set batch size
batch_size = 128
assert batch_size is not None, 'You must set the batch size'

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    # TODO: Train optimizer on all batches
    # for batch_features, batch_labels in ______
    for batch_features, batch_labels in batches(batch_size, train_features, train_labels):
        sess.run(optimizer, feed_dict={features: batch_features, labels: batch_labels})

    # Calculate accuracy for test dataset
    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))

Extracting /datasets/ud730/mnist\train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-labels-idx1-ubyte.gz
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Test Accuracy: 0.10000000149011612


## Epochs

### 训练一个模型 10 代的 TensorFlow 代码

In [44]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
import numpy as np

def print_epoch_stats(epoch_i, sess, last_features, last_labels):
    """
    Print cost and validation accuracy of an epoch
    """
    current_cost = sess.run(
        cost,
        feed_dict={features: last_features, labels: last_labels})
    valid_accuracy = sess.run(
        accuracy,
        feed_dict={features: valid_features, labels: valid_labels})
    if epoch_i%10==0:
        print('Epoch: {:<4} - Cost: {:<8.3} Valid Accuracy: {:<5.3}'.format(
        epoch_i,
        current_cost,
        valid_accuracy))

n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
valid_features = mnist.validation.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
valid_labels = mnist.validation.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
learning_rate = tf.placeholder(tf.float32)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

init = tf.global_variables_initializer()

batch_size = 128
epochs = 100
learn_rate = 0.1

train_batches = batches(batch_size, train_features, train_labels)

with tf.Session() as sess:
    sess.run(init)

    # Training cycle(run ALL data 'epochs' times)
    for epoch_i in range(epochs):

        # Loop over all batches(just run ALL optimizer one by one)
        for batch_features, batch_labels in train_batches:
            train_feed_dict = {
                features: batch_features,
                labels: batch_labels,
                learning_rate: learn_rate}
            sess.run(optimizer, feed_dict=train_feed_dict)

        # Print cost and validation accuracy of an epoch
        print_epoch_stats(epoch_i, sess, batch_features, batch_labels)

    # Calculate accuracy for test dataset
    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))

Extracting /datasets/ud730/mnist\train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist\t10k-labels-idx1-ubyte.gz
Epoch: 0    - Cost: 1.48     Valid Accuracy: 0.715
Epoch: 10   - Cost: 0.728    Valid Accuracy: 0.876
Epoch: 20   - Cost: 0.581    Valid Accuracy: 0.892
Epoch: 30   - Cost: 0.497    Valid Accuracy: 0.901
Epoch: 40   - Cost: 0.442    Valid Accuracy: 0.904
Epoch: 50   - Cost: 0.403    Valid Accuracy: 0.906
Epoch: 60   - Cost: 0.374    Valid Accuracy: 0.908
Epoch: 70   - Cost: 0.352    Valid Accuracy: 0.911
Epoch: 80   - Cost: 0.335    Valid Accuracy: 0.913
Epoch: 90   - Cost: 0.322    Valid Accuracy: 0.916
Test Accuracy: 0.9139999747276306


```python
# epoch = 10, lr = 0.001
Epoch: 0    - Cost: 11.0     Valid Accuracy: 0.204
Epoch: 1    - Cost: 9.95     Valid Accuracy: 0.229
Epoch: 2    - Cost: 9.18     Valid Accuracy: 0.246
Epoch: 3    - Cost: 8.59     Valid Accuracy: 0.264
Epoch: 4    - Cost: 8.13     Valid Accuracy: 0.283
Epoch: 5    - Cost: 7.77     Valid Accuracy: 0.301
Epoch: 6    - Cost: 7.47     Valid Accuracy: 0.316
Epoch: 7    - Cost: 7.2      Valid Accuracy: 0.328
Epoch: 8    - Cost: 6.96     Valid Accuracy: 0.342
Epoch: 9    - Cost: 6.73     Valid Accuracy: 0.36 
Test Accuracy: 0.3801000118255615
    
# epoch = 100, lr = 0.001
Epoch: 0    - Cost: 12.4     Valid Accuracy: 0.0838
Epoch: 10   - Cost: 6.02     Valid Accuracy: 0.266
Epoch: 20   - Cost: 4.36     Valid Accuracy: 0.414
Epoch: 30   - Cost: 3.55     Valid Accuracy: 0.516
Epoch: 40   - Cost: 3.05     Valid Accuracy: 0.583
Epoch: 50   - Cost: 2.7      Valid Accuracy: 0.63 
Epoch: 60   - Cost: 2.44     Valid Accuracy: 0.66 
Epoch: 70   - Cost: 2.24     Valid Accuracy: 0.684
Epoch: 80   - Cost: 2.08     Valid Accuracy: 0.703
Epoch: 90   - Cost: 1.94     Valid Accuracy: 0.719
Test Accuracy: 0.7305999994277954
```

## 实验准备
- 完成在 TensorFlow 中创建`单层神经网络`。
- 将实现数据规范化，然后使用 TensorFlow 构建和训练网络。        
---
- 问题1：标准化功能        
- 问题2：使用TensorFlow操作来创建特征，标签，重量和偏差张量        
- 问题3：调整学习速度，步数和批大小以获得最佳准确性     

In [1]:
### 另见文件 TensorFlow_nn.ipynb

## 两层神经网络
- 添加一个隐藏层到网络让它建模更复杂的功能。而且，在隐藏层上使用非线性激活函数可以模拟非线性函数。
    - ReLU隐藏层

示例代码：
```python
import tensorflow as tf
# Hidden Layer with ReLU activation function
# 隐藏层用 ReLU 作为激活函数
hidden_layer = tf.add(tf.matmul(features, hidden_weights), hidden_biases)
hidden_layer = tf.nn.relu(hidden_layer)

output = tf.add(tf.matmul(hidden_layer, output_weights), output_biases)
```

### 练习

In [8]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

output = None
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model(add hidden layer with weight and bias)
hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)

output = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])
    
# TODO: Print session results
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    print(sess.run(output))

[[ 5.11      8.440001]
 [ 0.        0.      ]
 [24.010002 38.24    ]]


### 深度神经网络

<img src="./imgs/tf_2lnn.jpg" width=360px>

In [1]:
# MNIST
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets(".", one_hot=True, reshape=False)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting .\train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting .\train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting .\t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting .\t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [2]:
import tensorflow as tf

# 多层神经网络的架构
# 参数 Parameters
learning_rate = 0.001
training_epochs = 20
batch_size = 128  # 如果没有足够内存，可以降低 batch size
display_step = 1

n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

In [3]:
# 隐藏层
n_hidden_layer = 256 # layer number of features 特征的层数

In [4]:
# 层权重和偏置项的储存
weights = {
    'hidden_layer': tf.Variable(tf.random_normal([n_input, n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_hidden_layer, n_classes]))
}
biases = {
    'hidden_layer': tf.Variable(tf.random_normal([n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

Instructions for updating:
Colocations handled automatically by placer.


In [5]:
# tf Graph input
x = tf.placeholder("float", [None, 28, 28, 1])
y = tf.placeholder("float", [None, n_classes])

x_flat = tf.reshape(x, [-1, n_input])

## 多层感知器

In [6]:
# Hidden layer with RELU activation
# ReLU作为隐藏层激活函数
layer_1 = tf.add(tf.matmul(x_flat, weights['hidden_layer']),biases['hidden_layer'])  # xw + b
layer_1 = tf.nn.relu(layer_1)                                                        # 把线性函数与 ReLU 组合在一起，形成一个2层网络

# Output layer with linear activation
# 输出层的线性激活函数
logits = tf.add(tf.matmul(layer_1, weights['out']), biases['out'])

In [7]:
# Define loss and optimizer
# 定义误差值和优化器
cost = tf.reduce_mean(\
    tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)\
    .minimize(cost)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [8]:
# Define loss and optimizer
# 定义误差值和优化器
cost = tf.reduce_mean(\
    tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)\
    .minimize(cost)

In [9]:
# Initializing the variables
# 初始化变量
init = tf.global_variables_initializer()

# Launch the graph
# 启动图
with tf.Session() as sess:
    sess.run(init)
    # Training cycle
    # 训练循环
    for epoch in range(training_epochs):
        total_batch = int(mnist.train.num_examples/batch_size)
        # Loop over all batches
        # 遍历所有 batch
        for i in range(total_batch):
            batch_x, batch_y = mnist.train.next_batch(batch_size)                    # 返回训练数据的一个mini-batch子集
            # Run optimization op (backprop) and cost op (to get loss value)
            # 运行优化器进行反向传导、计算 cost（获取 loss 值）
            sess.run(optimizer, feed_dict={x: batch_x, y: batch_y})

## 深度神经网络

<img src='./imgs/dnn.jpg' width-=360px>

就是这样！从一层到两层很简单。向网络中添加更多层，可以让你解决更复杂的问题。

## 模型

### 保存模型

In [12]:
import tensorflow as tf

"""存两个变量:weight, bias"""

# The file path to save the data
# 文件保存路径
save_file = './model.ckpt'

# Two Tensor Variables: weights and bias
# 两个 Tensor 变量：权重和偏置项
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
# 用来存取 Tensor 变量的类
saver = tf.train.Saver()

with tf.Session() as sess:
    # Initialize all the Variables
    # 初始化所有变量
    sess.run(tf.global_variables_initializer())

    # Show the values of weights and bias
   # 显示变量和权重
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

    # Save the model
    # 保存模型
    saver.save(sess, save_file)

Weights:
[[ 1.391076    0.5483249  -0.3649703 ]
 [ 0.05454035 -0.6986668   0.17243181]]
Bias:
[ 1.2168998  -0.45633256 -1.3427193 ]


### 读取模型

In [13]:
# Remove the previous weights and bias
# 移除之前的权重和偏置项
tf.reset_default_graph()

# Two Variables: weights and bias
# 两个变量：权重和偏置项
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
# 用来存取 Tensor 变量的类
saver = tf.train.Saver()

# 因为 tf.train.Saver.restore() 设定了 TensorFlow 变量，这里你不需要调用 tf.global_variables_initializer()了。
with tf.Session() as sess:
    # Load the weights and bias
    # 加载权重和偏置项
    saver.restore(sess, save_file)

    # Show the values of weights and bias
    # 显示权重和偏置项
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

INFO:tensorflow:Restoring parameters from ./model.ckpt
Weight:
[[ 0.6328563  -0.7062197   0.34345078]
 [-1.5923661  -0.13635351 -0.2057838 ]]
Bias:
[-1.7955613  -0.18664616  0.35228476]


### 保存一个训练好的模型

In [15]:
# Remove previous Tensors and Operations
# 移除之前的  Tensors 和运算
tf.reset_default_graph()

from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

learning_rate = 0.001
n_input = 784  # MNIST 数据输入 (图片尺寸: 28*28)
n_classes = 10  # MNIST 总计类别 (数字 0-9)

# Import MNIST data
# 加载 MNIST 数据
mnist = input_data.read_data_sets('.', one_hot=True)

# Features and Labels
# 特征和标签
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
# 权重和偏置项
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
# 定义损失函数和优化器
cost = tf.reduce_mean(\
    tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)\
    .minimize(cost)

# Calculate accuracy
# 计算准确率
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

Extracting .\train-images-idx3-ubyte.gz
Extracting .\train-labels-idx1-ubyte.gz
Extracting .\t10k-images-idx3-ubyte.gz
Extracting .\t10k-labels-idx1-ubyte.gz


In [17]:
# 训练并保存模型import math
import math

save_file = './train_model.ckpt'
batch_size = 128
n_epochs = 100

saver = tf.train.Saver()

# Launch the graph
# 启动图
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    # Training cycle
    # 训练循环
    for epoch in range(n_epochs):
        total_batch = math.ceil(mnist.train.num_examples / batch_size)

        # Loop over all batches
        # 遍历所有 batch
        for i in range(total_batch):
            batch_features, batch_labels = mnist.train.next_batch(batch_size)
            sess.run(
                optimizer,
                feed_dict={features: batch_features, labels: batch_labels})

        # Print status for every 10 epochs
        # 每运行10个 epoch 打印一次状态
        if epoch % 10 == 0:
            valid_accuracy = sess.run(
                accuracy,
                feed_dict={
                    features: mnist.validation.images,
                    labels: mnist.validation.labels})
            print('Epoch {:<3} - Validation Accuracy: {}'.format(
                epoch,
                valid_accuracy))

    # Save the model
    # 保存模型
    saver.save(sess, save_file)
    print('Trained Model Saved.')

Epoch 0   - Validation Accuracy: 0.12219999730587006
Epoch 10  - Validation Accuracy: 0.296999990940094
Epoch 20  - Validation Accuracy: 0.4291999936103821
Epoch 30  - Validation Accuracy: 0.5170000195503235
Epoch 40  - Validation Accuracy: 0.579200029373169
Epoch 50  - Validation Accuracy: 0.6233999729156494
Epoch 60  - Validation Accuracy: 0.652999997138977
Epoch 70  - Validation Accuracy: 0.678600013256073
Epoch 80  - Validation Accuracy: 0.6980000138282776
Epoch 90  - Validation Accuracy: 0.7110000252723694
Trained Model Saved.


### 加载训练好的模型

In [18]:
# 加载权重和偏置项，验证测试集准确率
saver = tf.train.Saver()

# Launch the graph
# 加载图
with tf.Session() as sess:
    saver.restore(sess, save_file)

    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: mnist.test.images, labels: mnist.test.labels})

print('Test Accuracy: {}'.format(test_accuracy))

INFO:tensorflow:Restoring parameters from ./train_model.ckpt
Test Accuracy: 0.7337999939918518


## 参数微调
- 很多时候你想调整，或者说“微调”一个你已经训练并保存了的模型。但是，把保存的变量直接加载到已经修改过的模型会产生错误。          
_让我们看看如何解决这个问题。_

### 命名报错
TensorFlow 对 Tensor 和计算使用一个叫 name 的字符串辨识器，如果没有定义 name，TensorFlow 会自动创建一个。                     
TensorFlow 会把第一个节点命名为 <Type>，把后续的命名为<Type>_<number>。   
    
_让我们看看这对加载一个有不同顺序权重和偏置项的模型有哪些影响：_

In [20]:
# import tensorflow as tf

# # Remove the previous weights and bias
# # 移除先前的权重和偏置项
# tf.reset_default_graph()

# save_file = 'model.ckpt'

# # Two Tensor Variables: weights and bias
# # 两个 Tensor 变量：权重和偏置项
# weights = tf.Variable(tf.truncated_normal([2, 3]))
# bias = tf.Variable(tf.truncated_normal([3]))

# saver = tf.train.Saver()

# # Print the name of Weights and Bias
# # 打印权重和偏置项的名字
# print('Save Weights: {}'.format(weights.name))
# print('Save Bias: {}'.format(bias.name))

# with tf.Session() as sess:
#     sess.run(tf.global_variables_initializer())
#     saver.save(sess, save_file)

# # Remove the previous weights and bias
# # 移除之前的权重和偏置项
# tf.reset_default_graph()

# # Two Variables: weights and bias
# # 两个变量：权重和偏置项
# bias = tf.Variable(tf.truncated_normal([3]))
# weights = tf.Variable(tf.truncated_normal([2, 3]))

# saver = tf.train.Saver()

# # Print the name of Weights and Bias
# # 打印权重和偏置项的名字
# print('Load Weights: {}'.format(weights.name))
# print('Load Bias: {}'.format(bias.name))

# with tf.Session() as sess:
#     # Load the weights and bias - ERROR
#     # 加载权重和偏置项 - 报错
#     saver.restore(sess, save_file)

```python
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match.
```

你注意到， __`weights` 和 `bias` 的 `name` 属性与你保存的模型不同__ 。这是为什么代码报`“Assign requires shapes of both tensors to match”`这个错误。
saver.restore(sess, save_file) 代码试图把 __权重数据加载到bias里，把偏置项数据加载到 weights里__

In [21]:
# 手动设定 name 属性
import tensorflow as tf

tf.reset_default_graph()

save_file = 'model.ckpt'

# Two Tensor Variables: weights and bias
# 两个 Tensor 变量：权重和偏置项
weights = tf.Variable(tf.truncated_normal([2, 3]), name='weights_0')
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')

saver = tf.train.Saver()

# Print the name of Weights and Bias
# 打印权重和偏置项的名称
print('Save Weights: {}'.format(weights.name))
print('Save Bias: {}'.format(bias.name))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver.save(sess, save_file)

# Remove the previous weights and bias
# 移除之前的权重和偏置项
tf.reset_default_graph()

# Two Variables: weights and bias
# 两个变量：权重和偏置项
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')
weights = tf.Variable(tf.truncated_normal([2, 3]) ,name='weights_0')

saver = tf.train.Saver()

# Print the name of Weights and Bias
# 打印权重和偏置项的名称
print('Load Weights: {}'.format(weights.name))
print('Load Bias: {}'.format(bias.name))

with tf.Session() as sess:
    # Load the weights and bias - No Error
    # 加载权重和偏置项 - 没有报错
    saver.restore(sess, save_file)

print('Loaded Weights and Bias successfully.')

Save Weights: weights_0:0
Save Bias: bias_0:0
Load Weights: weights_0:0
Load Bias: bias_0:0
INFO:tensorflow:Restoring parameters from model.ckpt
Loaded Weights and Bias successfully.


## Dropout
- Dropout 是一个降低过拟合的正则化技术。它在网络中暂时的丢弃一些单元（神经元），以及与它们的前后相连的所有节点

<img src='./imgs/dropout.jpg' width=360px>

示例代码：
```python
keep_prob = tf.placeholder(tf.float32) # probability to keep units

hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)
hidden_layer = tf.nn.dropout(hidden_layer, keep_prob)

logits = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])
```

上面的代码展示了如何在神经网络中应用 dropout。

`tf.nn.dropout()` 函数有两个参数：   

- `hidden_layer`：你要应用 dropout 的 tensor         
- `keep_prob`：任何一个给定单元的留存率（没有被丢弃的单元）  

`keep_prob` 可以让你调整丢弃单元的数量。为了补偿被丢弃的单元，`tf.nn.dropout()` 把所有保留下来的单元（没有被丢弃的单元）* 1/keep_prob   

在 __训练__ 时，一个好的keep_prob初始值是 `0.5` 。    

在 __测试__ 时，把 keep_prob 值设为 `1.0` ，这样保留所有的单元，最大化模型的能力。   

In [26]:
# 这个练习的代码来自 ReLU 的练习，应用一个 dropout 层。
# 用 ReLU 层和 dropout 层构建一个模型，keep_prob值设为 0.5。打印这个模型的 logits。

# Solution is available in the other "solution.py" tab
import tensorflow as tf

hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[0.0, 2.0, 3.0, 4.0], [0.1, 0.2, 0.3, 0.4], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model with Dropout
keep_prob = tf.placeholder(tf.float32)                                 # define a prob by 'placeholder'
hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)
hidden_layer = tf.nn.dropout(hidden_layer, rate=(1-keep_prob))                  # add a dropout by prob

logits = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])

# TODO: Print logits from a session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(logits, feed_dict={keep_prob: 0.5}))

[[ 8.46        9.4       ]
 [ 0.30800003  0.7700001 ]
 [14.280001   33.100002  ]]


__END__      